<?php
/**
 * Api
 * PHP version 7.2
 *
 * @category Class
 * @package  QvaPay
 * @author   Carlos Batista
 * @link     https://github.com/cbatista8a/
 */

/**
 * Qvapay
 *
 * QvaPay PHP Api Client
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/cbatista8a/
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://github.com/cbatista8a/).
 * https://github.com/cbatista8a/
 * Do not edit the class manually.
 */

namespace QvaPay;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use QvaPayException;
use QvaPay\Configuration;
use QvaPay\HeaderSelector;
use QvaPay\ObjectSerializer;

/**
 * Api Class Doc Comment
 *
 * @category Class
 * @package  QvaPay
 * @author   Carlos Batista
 * @link     https://github.com/cbatista8a/
 */
class Api
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex)
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation auth
     *
     * Autenticación vía API
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     *
     * @throws \QvaPayException on non-2xx response
     * @throws \InvalidArgumentException
     * @return string[]
     */
    public function auth($app_id, $app_secret)
    {
        list($response) = $this->authWithHttpInfo($app_id, $app_secret);
        return $response;
    }

    /**
     * Operation authWithHttpInfo
     *
     * Autenticación vía API
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     *
     * @throws \QvaPayException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of string[], HTTP status code, HTTP response headers (array of strings)
     */
    public function authWithHttpInfo($app_id, $app_secret)
    {
        $request = $this->authRequest($app_id, $app_secret);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('string[]' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'string[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'string[]';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation authAsync
     *
     * Autenticación vía API
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authAsync($app_id, $app_secret)
    {
        return $this->authAsyncWithHttpInfo($app_id, $app_secret)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation authAsyncWithHttpInfo
     *
     * Autenticación vía API
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function authAsyncWithHttpInfo($app_id, $app_secret)
    {
        $returnType = 'string[]';
        $request = $this->authRequest($app_id, $app_secret);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'auth'
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function authRequest($app_id, $app_secret)
    {
        // verify the required parameter 'app_id' is set
        if ($app_id === null || (is_array($app_id) && count($app_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_id when calling auth'
            );
        }
        // verify the required parameter 'app_secret' is set
        if ($app_secret === null || (is_array($app_secret) && count($app_secret) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_secret when calling auth'
            );
        }

        $resourcePath = '/info';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($app_id !== null) {
            if('form' === 'form' && is_array($app_id)) {
                foreach($app_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['app_id'] = $app_id;
            }
        }
        // query params
        if ($app_secret !== null) {
            if('form' === 'form' && is_array($app_secret)) {
                foreach($app_secret as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['app_secret'] = $app_secret;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation balance
     *
     * Consultar saldo QvaPay
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     *
     * @throws \QvaPayException on non-2xx response
     * @throws \InvalidArgumentException
     * @return string[]
     */
    public function balance($app_id, $app_secret)
    {
        list($response) = $this->balanceWithHttpInfo($app_id, $app_secret);
        return $response;
    }

    /**
     * Operation balanceWithHttpInfo
     *
     * Consultar saldo QvaPay
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     *
     * @throws \QvaPayException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of string[], HTTP status code, HTTP response headers (array of strings)
     */
    public function balanceWithHttpInfo($app_id, $app_secret)
    {
        $request = $this->balanceRequest($app_id, $app_secret);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('string[]' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'string[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'string[]';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation balanceAsync
     *
     * Consultar saldo QvaPay
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function balanceAsync($app_id, $app_secret)
    {
        return $this->balanceAsyncWithHttpInfo($app_id, $app_secret)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation balanceAsyncWithHttpInfo
     *
     * Consultar saldo QvaPay
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function balanceAsyncWithHttpInfo($app_id, $app_secret)
    {
        $returnType = 'string[]';
        $request = $this->balanceRequest($app_id, $app_secret);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'balance'
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function balanceRequest($app_id, $app_secret)
    {
        // verify the required parameter 'app_id' is set
        if ($app_id === null || (is_array($app_id) && count($app_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_id when calling balance'
            );
        }
        // verify the required parameter 'app_secret' is set
        if ($app_secret === null || (is_array($app_secret) && count($app_secret) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_secret when calling balance'
            );
        }

        $resourcePath = '/balance';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($app_id !== null) {
            if('form' === 'form' && is_array($app_id)) {
                foreach($app_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['app_id'] = $app_id;
            }
        }
        // query params
        if ($app_secret !== null) {
            if('form' === 'form' && is_array($app_secret)) {
                foreach($app_secret as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['app_secret'] = $app_secret;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation invoice
     *
     * Crear factura de pago
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     * @param  float $amount Cantidad de dinero a recibir (en dólares y con 2 decimales) (required)
     * @param  string $description Descripción de la factura a generar, útil para brindar información al pagador. (No más de 300 caracteres) (required)
     * @param  bool $signed Generación de una URL firmada o no (URL firmadas vencen a los 30 minutos, aportando más seguridad o caducidad) (required)
     * @param  string $remote_id ID de factura en el sistema remoto (no requerido) (optional)
     *
     * @throws \QvaPayException on non-2xx response
     * @throws \InvalidArgumentException
     * @return string[]
     */
    public function invoice($app_id, $app_secret, $amount, $description, $signed, $remote_id = null)
    {
        list($response) = $this->invoiceWithHttpInfo($app_id, $app_secret, $amount, $description, $signed, $remote_id);
        return $response;
    }

    /**
     * Operation invoiceWithHttpInfo
     *
     * Crear factura de pago
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     * @param  float $amount Cantidad de dinero a recibir (en dólares y con 2 decimales) (required)
     * @param  string $description Descripción de la factura a generar, útil para brindar información al pagador. (No más de 300 caracteres) (required)
     * @param  bool $signed Generación de una URL firmada o no (URL firmadas vencen a los 30 minutos, aportando más seguridad o caducidad) (required)
     * @param  string $remote_id ID de factura en el sistema remoto (no requerido) (optional)
     *
     * @throws \QvaPayException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of string[], HTTP status code, HTTP response headers (array of strings)
     */
    public function invoiceWithHttpInfo($app_id, $app_secret, $amount, $description, $signed, $remote_id = null)
    {
        $request = $this->invoiceRequest($app_id, $app_secret, $amount, $description, $signed, $remote_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('string[]' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'string[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'string[]';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation invoiceAsync
     *
     * Crear factura de pago
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     * @param  float $amount Cantidad de dinero a recibir (en dólares y con 2 decimales) (required)
     * @param  string $description Descripción de la factura a generar, útil para brindar información al pagador. (No más de 300 caracteres) (required)
     * @param  bool $signed Generación de una URL firmada o no (URL firmadas vencen a los 30 minutos, aportando más seguridad o caducidad) (required)
     * @param  string $remote_id ID de factura en el sistema remoto (no requerido) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoiceAsync($app_id, $app_secret, $amount, $description, $signed, $remote_id = null)
    {
        return $this->invoiceAsyncWithHttpInfo($app_id, $app_secret, $amount, $description, $signed, $remote_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation invoiceAsyncWithHttpInfo
     *
     * Crear factura de pago
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     * @param  float $amount Cantidad de dinero a recibir (en dólares y con 2 decimales) (required)
     * @param  string $description Descripción de la factura a generar, útil para brindar información al pagador. (No más de 300 caracteres) (required)
     * @param  bool $signed Generación de una URL firmada o no (URL firmadas vencen a los 30 minutos, aportando más seguridad o caducidad) (required)
     * @param  string $remote_id ID de factura en el sistema remoto (no requerido) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function invoiceAsyncWithHttpInfo($app_id, $app_secret, $amount, $description, $signed, $remote_id = null)
    {
        $returnType = 'string[]';
        $request = $this->invoiceRequest($app_id, $app_secret, $amount, $description, $signed, $remote_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'invoice'
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     * @param  float $amount Cantidad de dinero a recibir (en dólares y con 2 decimales) (required)
     * @param  string $description Descripción de la factura a generar, útil para brindar información al pagador. (No más de 300 caracteres) (required)
     * @param  bool $signed Generación de una URL firmada o no (URL firmadas vencen a los 30 minutos, aportando más seguridad o caducidad) (required)
     * @param  string $remote_id ID de factura en el sistema remoto (no requerido) (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function invoiceRequest($app_id, $app_secret, $amount, $description, $signed, $remote_id = null)
    {
        // verify the required parameter 'app_id' is set
        if ($app_id === null || (is_array($app_id) && count($app_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_id when calling invoice'
            );
        }
        // verify the required parameter 'app_secret' is set
        if ($app_secret === null || (is_array($app_secret) && count($app_secret) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_secret when calling invoice'
            );
        }
        // verify the required parameter 'amount' is set
        if ($amount === null || (is_array($amount) && count($amount) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $amount when calling invoice'
            );
        }
        // verify the required parameter 'description' is set
        if ($description === null || (is_array($description) && count($description) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $description when calling invoice'
            );
        }
        // verify the required parameter 'signed' is set
        if ($signed === null || (is_array($signed) && count($signed) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $signed when calling invoice'
            );
        }

        $resourcePath = '/create_invoice';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($app_id !== null) {
            if('form' === 'form' && is_array($app_id)) {
                foreach($app_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['app_id'] = $app_id;
            }
        }
        // query params
        if ($app_secret !== null) {
            if('form' === 'form' && is_array($app_secret)) {
                foreach($app_secret as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['app_secret'] = $app_secret;
            }
        }
        // query params
        if ($amount !== null) {
            if('form' === 'form' && is_array($amount)) {
                foreach($amount as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['amount'] = $amount;
            }
        }
        // query params
        if ($description !== null) {
            if('form' === 'form' && is_array($description)) {
                foreach($description as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['description'] = $description;
            }
        }
        // query params
        if ($signed !== null) {
            if('form' === 'form' && is_array($signed)) {
                foreach($signed as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['signed'] = $signed;
            }
        }
        // query params
        if ($remote_id !== null) {
            if('form' === 'form' && is_array($remote_id)) {
                foreach($remote_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['remote_id'] = $remote_id;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation transactions
     *
     * Obtener Transacciones
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     *
     * @throws \QvaPayException on non-2xx response
     * @throws \InvalidArgumentException
     * @return string[]
     */
    public function transactions($app_id, $app_secret)
    {
        list($response) = $this->transactionsWithHttpInfo($app_id, $app_secret);
        return $response;
    }

    /**
     * Operation transactionsWithHttpInfo
     *
     * Obtener Transacciones
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     *
     * @throws \QvaPayException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of string[], HTTP status code, HTTP response headers (array of strings)
     */
    public function transactionsWithHttpInfo($app_id, $app_secret)
    {
        $request = $this->transactionsRequest($app_id, $app_secret);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('string[]' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'string[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'string[]';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'string[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation transactionsAsync
     *
     * Obtener Transacciones
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transactionsAsync($app_id, $app_secret)
    {
        return $this->transactionsAsyncWithHttpInfo($app_id, $app_secret)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation transactionsAsyncWithHttpInfo
     *
     * Obtener Transacciones
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function transactionsAsyncWithHttpInfo($app_id, $app_secret)
    {
        $returnType = 'string[]';
        $request = $this->transactionsRequest($app_id, $app_secret);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'transactions'
     *
     * @param  string $app_id App ID (required)
     * @param  string $app_secret App Secret (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function transactionsRequest($app_id, $app_secret)
    {
        // verify the required parameter 'app_id' is set
        if ($app_id === null || (is_array($app_id) && count($app_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_id when calling transactions'
            );
        }
        // verify the required parameter 'app_secret' is set
        if ($app_secret === null || (is_array($app_secret) && count($app_secret) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $app_secret when calling transactions'
            );
        }

        $resourcePath = '/transactions';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($app_id !== null) {
            if('form' === 'form' && is_array($app_id)) {
                foreach($app_id as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['app_id'] = $app_id;
            }
        }
        // query params
        if ($app_secret !== null) {
            if('form' === 'form' && is_array($app_secret)) {
                foreach($app_secret as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['app_secret'] = $app_secret;
            }
        }




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
